name: manarah
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  hijri: ^3.0.0
  intl: ^0.19.0
  geolocator: ^13.0.4
  image_picker: ^0.8.7+5
  geocoding: ^3.0.0
  dio: ^5.7.0
  get_it: ^7.6.0
  flutter_qiblah: ^3.0.0
  flutter_svg: ^2.0.0
  path_provider:
  flutter_pdfview:
  google_maps_flutter: ^2.3.0
  shared_preferences: ^2.3.2
  connectivity_plus:
  equatable: ^2.0.5
  device_preview: ^1.1.0
  flutter_native_splash:
  just_audio:
flutter_native_splash:
  color: "#203AA2"
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "Assets/Frame 249.png"
  background_color: "#152216"
  adaptive_icon_background: "#152216"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - Assets/
    - Assets/data.json
  fonts:
    - family: Almarai
      fonts:
        - asset: Assets/Fonts/Almarai-Regular.ttf
